### PR TITLE
Updated to work with current Timber version

### PR DESCRIPTION
**Pull request by domenukk**
Your Tree didn't work with the current version. Seems like some stuff changed.

### CODE REVIEW

**Comment by ypresto** [comment]
Thanks for PR!

timber version in build.gradle should be updated, and every v/d/i/w/e methods are not necessary anymore.

I'll take over these tasks. :)

**Comment by ypresto** [comment]
Sorry for being late, v1.0.0 has been released!

**Comment by ypresto** [comment]
(Note that class and package names has been changed.)

**Comment by domenukk** [comment]
No worries, thanks for the lib.

**Pull request closed without merging**
